name: spotify_explode
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  dio: ^5.4.3+1
  logger: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  audioplayers: ^6.0.0
  audio_video_progress_bar: ^2.0.2
  html: ^0.15.4
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
